        
- name: firewall config for control plane
  hosts: control_plane
  become: true
  roles:
   - master_firewall

- name: firewall config for node plane
  hosts: node_plane
  become: true
  roles:
   - worker_firewall

- name: Run on all nodes
  hosts: all
  become: true
  roles:
   - common_config_for_all_nodes

- name: initializing kubernetes cluster
  hosts: control_plane
  become: true
  roles:
   - initialize_kubernetes_cluster

- name: join worker nodes
  hosts: node_plane
  become: true
  roles:
   - join_worker_node

- name: configure monitoring 
  hosts: control_plane
  become: true
  roles:
   - configure_monitoring 