---
# tasks file for initialize_kubernetes_cluster

- name: initialize kubernetes cluster
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }}
  args:
   creates: /etc/kubernetes/admin.conf

- name: Creating .kube directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Copying /etc/kubernetes/admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    mode: "0600"
    remote_src: true


- name: Copy calico.yaml
  ansible.builtin.copy:
    src: calico.yaml
    dest: /tmp/calico.yaml

- name: Apply Calico CNI manifest
  ansible.builtin.command: kubectl apply -f /tmp/calico.yaml --kubeconfig=/home/yussuf/.kube/config



- name: Register the kubeadm join command
  shell: kubeadm token create --print-join-command
  register: join_cmd_result

- name: Set join command as fact
  set_fact:
    joining_command_fact: "{{ join_cmd_result.stdout }}"
