---
# tasks file for configure_monitoring

- name: Copy custom.yaml  
  ansible.builtin.copy:
    src: custom.yaml  
    dest: /tmp/custom.yaml  

- name: install metrics server
  ansible.builtin.command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml --kubeconfig=/home/yussuf/.kube/config



- name: Patch Metrics Server to Allow Insecure TLS Connections to Kubelets
  ansible.builtin.command: >
    kubectl patch deployment metrics-server -n kube-system
    --type=json
    -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--kubelet-insecure-tls"}]'
    --kubeconfig=/home/yussuf/.kube/config




- name: restart metrics server
  ansible.builtin.command: kubectl rollout restart deployment metrics-server -n kube-system --kubeconfig=/home/yussuf/.kube/config


- name: Check if Helm is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_installed

- name: Download Helm archive
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.13.0-rc.1-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
  when: not helm_installed.stat.exists

- name: Extract Helm archive
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/
    remote_src: yes
    extra_opts: [--skip-old-files]
  when: not helm_installed.stat.exists

- name: Move Helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: yes
  when: not helm_installed.stat.exists



- name: add ingress nginx helm repo
  ansible.builtin.command: /usr/local/bin/helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx



- name: Add prometheus-community helm repo
  ansible.builtin.command: /usr/local/bin/helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: update helm repo
  ansible.builtin.command: /usr/local/bin/helm repo update


- name: install ingress-nginx 
  ansible.builtin.command: /usr/local/bin/helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --set controller.service.type=NodePort --set controller.service.nodePorts.http=30080 --set controller.service.nodePorts.https=30443 --kubeconfig=/home/yussuf/.kube/config


- name: install prometheus-stack
  ansible.builtin.command: /usr/local/bin/helm upgrade --install  my-kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 75.15.1 --namespace myprom --create-namespace -f /tmp/custom.yaml --kubeconfig=/home/yussuf/.kube/config